Update queue type to avoid build error (#673)
* Update queue type to avoid build error

Existing code gives this error

node_modules/langchain/dist/util/async_caller.d.ts:30:22 - error TS2702: 'PQueueMod' only refers to a type, but is being used as a namespace here.
30     protected queue: PQueueMod.default;

This PR fixes it..

* Update langchain/src/util/async_caller.ts

---------

Co-authored-by: Nuno Campos <nuno@boringbits.io>